name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven test
      run: mvn -B package --file pom.xml
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
    -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rakesh09867/my-app:985627
    
